# 登录url
login_info:
  login_url: http://localhost/api/mgr/loginReq
  username: auto
  password: sdfsdfsdf

# 课程url
course_url:  http://localhost/api/mgr/sq_mgr/

# 项目路径
prj_path:  H:/api_auto_test_frame